### ISSUE TITLE
Curate system diagrams to make sure they render

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/docs#16]
source:
https://github.com/eosnetworkfoundation/docs/blob/main/docs/03_tutorials/20_tic-tac-toe-game-smart-contract-single-node.md#tutorial-workflow

view: (doesn't render properly)
http://docs.eosnetwork.com/docs/latest/tutorials/tic-tac-toe-game-smart-contract-single-node#tutorial-workflow

**Comment by nsjames** [comment]
Doesn't seem to be an issue any longer.
