### ISSUE TITLE
SPIKE - Curate EOSIO references prior to Antelope

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/docs#17]
Identify the occurrences of EOSIO in antelope and ENF repositories and create discussions around each found item so that we can understand what needs to be done in following tasks

AC: 
- Find leftover occurrences `EOSIO` in the following repositories: 
  - welcome
  - cdt
  - leap
  - contracts
  - dune?
  - other?
- Create a ticket (or tickets) to capture the work needed to answer the case-by-case basis

**Comment by VEG-Ginna** [comment]
I vote to remove the sentence or paragraph that contains the reference. If
we need to add it back in for a particular reason, we can.
