### ISSUE TITLE
Update the release url for reference-contracts in the "Deploy, Issue and Transfer Tokens" for ENF docs

### ISSUE THREAD

**Issue by iamveritas** [eosnetworkfoundation/docs#20]
Need a link to reference contracts release from AntelopeIO.org

in the "Deploy, Issue and Transfer Token" for ENF documentations the path to the latest release for reference contracts should be the one in AntelopeIO org (https://github.com/AntelopeIO/reference-contracts/releases) not the one in the eosnetworkfoundation org as it is now.

this issue can not be resolved until there is at least one release for the **reference contracts** in the AntelopeIO org; at the time when I am filing this issue there's no release yet.

AC:
- Provide the working valid link

Next Steps:
- Set up issue for link for EOS

**Comment by nsjames** [comment]
We are reworking this anyway so I will close this out for now. We can re-open later if it's still an issue.
