### ISSUE TITLE
Secp256r1 signing and verification of signatures with Smart Contract

### ISSUE THREAD

**Issue by adolfommoyano** [eosnetworkfoundation/docs#22]
Hi, I am new with eosio Smart Contracts development. I need to sign messages and verify signatures of ghetto curve secp256r1. How do I include external libraries for c in a Smart Contract? Thanks in advance.

**Comment by nsjames** [comment]
This is the wrong place for this question, best to ask in our chats:

Telegram: https://t.me/antelopedevs
Discord: https://discord.com/channels/892385699616153600/1042216000491372604
