### ISSUE TITLE
Command doesn't work anymore because the history plugin has been removed

### ISSUE THREAD

**Issue by greg7mdp** [eosnetworkfoundation/docs#36]
See https://github.com/eosnetworkfoundation/docs/blob/0736f718d5396226d36e0a5247aad27950ccfc51/docs/02_getting-started/03_smart-contract-development/06_adding-inline-actions.md?plain=1#L327-L335

**Comment by nsjames** [comment]
Thanks for the report, we're superseding all of these smart contract tutorials with a [new one](https://github.com/eosnetworkfoundation/devrel/issues/168). 

Closing this ticket so it doesn't linger.
