### ISSUE TITLE
Incorrect example code

### ISSUE THREAD

**Issue by jolly-fellow** [eosnetworkfoundation/docs#50]
On this page https://docs.eosnetwork.com/docs/latest/getting-started/smart-contract-development/hello-world
The code:

```c++
#include <eosio/eosio.hpp>

using namespace eosio;

class [[eosio::contract]] hello : public contract {
  public:
      using contract::contract;

      [[eosio::action]]
      void hi( name user ) {
         print( "Hello, ", user);
      }
};
```

is repeating three times. It seems the first time it should not have `[[eosio::action]]` because this attribute is described right after this code and the second example shows how  the first example looks with this attribute.

**Comment by nsjames** [comment]
Hey @jolly-fellow thanks for the report 🙏

We're in the middle of completely rewriting a superseding guide for smart contracts (https://github.com/eosnetworkfoundation/devrel/issues/168) 

I'm going to close this issue out so that it doesn't linger, but appreciate the due diligence!
